name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Image
        run: docker build -t yourdockerhub/backend ./backend

      - name: Build Frontend Image
        run: docker build -t yourdockerhub/frontend ./frontend

      - name: Push Backend Image
        run: docker push yourdockerhub/backend

      - name: Push Frontend Image
        run: docker push yourdockerhub/frontend